module.exports = [
  '#!/bin/sh',
  '# LICENSE [Anti 996 License](https://github.com/jeasonstudio/git-hook-996/blob/master/LICENSE)',
  '# Author Jeason',
  '',
  'WEEK_DAY=$(date +%a)',
  'HOUR=$(date +%H)',
  'HUM_TIME="$(date +%X) $(date +%A)"',
  'error_log() {',
  '  echo ""',
  '  echo "🚫   \\033[31mForbid commit at $HUM_TIME!!\\033[0m"',
  '  echo "🚫   \\033[31mMore information: https://996.icu\\033[0m"',
  '}',
  '# Sat or Sun forbidden',
  'if [[ $WEEK_DAY = "Sat" || $WEEK_DAY = "Sun" ]]',
  'then',
  '  error_log',
  '  exit 1',
  'fi',
  'if [[ $HOUR -lt 9 || $HOUR -gt 18 ]]',
  'then',
  '  error_log',
  '  exit 1',
  'fi',
  'echo ""',
  'echo "🎁   \\033[32m$HUM_TIME allowed to commit.\\033[0m"',
  'echo "🎁   \\033[32mHapply coding.\\033[0m"',
  'exit 0',
  '',
];
